apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-reader-rolebinding
  namespace: common
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: jsh # "name" is case sensitive
  namespace: common
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole # this must be Role or ClusterRole
  name: node-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
