apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: get-node-info
  namespace: common
  labels:
    app: get-node-info
spec:
  selector:
    matchLabels:
      app: get-node-info
  template:
    metadata:
      labels:
        app: get-node-info
    spec:
      serviceAccountName: jsh
      automountServiceAccountToken: true
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: app
        image: asdfry/get-node-info:20230801
        imagePullPolicy: Always
        command: ["python", "app/main.py", "--duration", "3600"]
        securityContext:
          privileged: true
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
